# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: jar --scan
    - name: Upload Fat Jar
      uses: actions/upload-artifact@v3
      with:
        name: OcHD-App
        path: build/libs/*.jar
  make-texture:
    needs: build
    strategy:
      matrix:
        size: [ 4096, 2048, 1024, 512, 256, 128, 64, 32 ]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Download Fat Jar
      uses: actions/download-artifact@v3
      with:
        name: OcHD-App
    - name: Make Textures
      run: java -Dprism.maxvram=2G -XX:+UseStringDeduplication -Xms4608M -Xmx4608M '-Xlog:gc*=debug,gc+heap=trace,gc+heap+exit=trace,gc+metaspace=trace,gc+nmethod=info' -XX:+UnlockExperimentalVMOptions -XX:+UseParallelGC -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -jar OcHd-KotlinBuild-1.0-SNAPSHOT.jar ${{ matrix.size }}
    - name: Zip Texture Pack
      run: cd pngout && zip -r OcHD-${{ matrix.size}}x${{ matrix.size}}.zip *
    - name: Publish Texture Pack
      uses: actions/upload-artifact@v3
      with:
        name: OcHD ${{ matrix.size }}x${{ matrix.size }}
        path: 'pngout/OcHD-${{ matrix.size}}x${{ matrix.size}}.zip'
